

/**
 * BUSINESS PROFILE
 */

export const CLEAR_BUSINESS_PROFILE_ERROR = "CLEAR_BUSINESS_PROFILE_ERROR"

// API Calls
export const ADD_BUSINESS_PROFILE_SUCCESS = "ADD_BUSINESS_PROFILE_SUCCESS";
export const ADD_BUSINESS_PROFILE_FAILURE = "ADD_BUSINESS_PROFILE_FAILURE";

export const GET_BUSINESS_PROFILES_SUCCESS = "GET_BUSINESS_PROFILES_SUCCESS";
export const GET_BUSINESS_PROFILES_FAILURE = "GET_BUSINESS_PROFILES_FAILURE"

export const UPDATE_BUSINESS_PROFILE_SUCCESS = "UPDATE_BUSINESS_PROFILE_SUCCESS";
export const UPDATE_BUSINESS_PROFILE_FAILURE = "UPDATE_BUSINESS_PROFILE_FAILURE";

export const DELETE_BUSINESS_PROFILE_SUCCESS = "DELETE_BUSINESS_PROFILE_SUCCESS";
export const DELETE_BUSINESS_PROFILE_FAILURE = "DELETE_BUSINESS_PROFILE_FAILURE";

// STORE Calls
export const SET_CURRENT_BUSINESS_PROFILE_ACTION = "GET_CURRENT_BUSINESS_PROFILE_ACTION";



/**
 * BUSINESS SESSION
 */

export const CLEAR_BUSINESS_SESSION_ERROR = "CLEAR_BUSINESS_SESSION_ERROR"

// API Calls
export const ADD_BUSINESS_SESSION_SUCCESS = "ADD_BUSINESS_SESSION_SUCCESS";
export const ADD_BUSINESS_SESSION_FAILURE = "ADD_BUSINESS_SESSION_FAILURE";

export const GET_BUSINESS_SESSION_SUCCESS = "GET_BUSINESS_SESSION_SUCCESS";
export const GET_BUSINESS_SESSION_FAILURE = "GET_BUSINESS_SESSION_FAILURE";

export const GET_ALL_BUSINESS_SESSIONS_SUCCESS = "GET_ALL_BUSINESS_SESSIONS_SUCCESS";
export const GET_ALL_BUSINESS_SESSIONS_FAILURE = "GET_ALL_BUSINESS_SESSIONS_FAILURE";

export const GET_AVAILABLE_BUSINESS_SESSIONS_SUCCESS = "GET_AVAILABLE_BUSINESS_SESSIONS_SUCCESS";
export const GET_AVAILABLE_BUSINESS_SESSIONS_FAILURE = "GET_AVAILABLE_BUSINESS_SESSIONS_FAILURE";

export const GET_REGISTERED_BUSINESS_SESSIONS_SUCCESS = "GET_REGISTERED_BUSINESS_SESSIONS_SUCCESS";
export const GET_REGISTERED_BUSINESS_SESSIONS_FAILURE = "GET_REGISTERED_BUSINESS_SESSIONS_FAILURE";

export const REGISTER_BUSINESS_SESSIONS_SUCCESS = "REGISTER_BUSINESS_SESSIONS_SUCCESS";
export const REGISTER_BUSINESS_SESSIONS_FAILURE = "REGISTER_BUSINESS_SESSIONS_FAILURE";

export const UPDATE_BUSINESS_SESSIONS_SUCCESS = "UPDATE_BUSINESS_SESSIONS_SUCCESS";
export const UPDATE_BUSINESS_SESSIONS_FAILURE = "UPDATE_BUSINESS_SESSIONS_FAILURE";

export const DELETE_BUSINESS_SESSION_SUCCESS = "DELETE_BUSINESS_SESSION_SUCCESS";
export const DELETE_BUSINESS_SESSION_FAILURE = "DELETE_BUSINESS_SESSION_FAILURE";

export const GET_EXERCISES_SESSION_SUCCESS = "GET_EXERCISES_SESSION_SUCCESS";
export const GET_EXERCISES_SESSION_FAILURE = "GET_EXERCISES_SESSION_FAILURE";

export const GET_EXERCISE_PROD_SESSION_SUCCESS = "GET_EXERCISE_PROD_SESSION_SUCCESS";
export const GET_EXERCISE_PROD_SESSION_FAILURE = "GET_EXERCISE_PROD_SESSION_FAILURE";

export const GET_BUSINESS_SESSION_STATS_SUCCESS = "GET_BUSINESS_SESSION_STATS_SUCCESS";
export const GET_BUSINESS_SESSION_STATS_FAILURE = "GET_BUSINESS_SESSION_STATS_FAILURE";

// STORE Calls
export const CLEAR_CURRENT_BUSINESS_SESSION_STATS_ACTION = "CLEAR_CURRENT_BUSINESS_SESSION_STATS_ACTION";
export const CLEAR_CURRENT_BUSINESS_SESSION_ACTION = "CLEAR_CURRENT_BUSINESS_SESSION_ACTION"
export const CLEAR_EXERCISES_FOR_SESSSION_ACTION = "CLEAR_EXERCISES_FOR_SESSSION_ACTION"

export const UPDATE_BUSINESS_SESSIONS_PARTIAL_WARN = "UPDATE_BUSINESS_SESSIONS_PARTIAL_WARN";





/**
 * EXERCISE PRODUCTION
 */

export const CLEAR_EXERCISE_PRODUCTION_ERROR = "CLEAR_EXERCISE_PRODUCTION_ERROR"

// API Calls
export const SEND_EXERCISE_PRODUCTION_SUCCESS = "SEND_EXERCISE_PRODUCTION_SUCCESS"
export const SEND_EXERCISE_PRODUCTION_FAILURE = "SEND_EXERCISE_PRODUCTION_FAILURE"





/**
 * EXERCISE
 */

export const CLEAR_EXERCISE_ERROR = "CLEAR_EXERCISE_ERROR"

// API Calls
export const ADD_EXERCISE_SUCCESS = "ADD_EXERCISE_SUCCESS";
export const ADD_EXERCISE_FAILURE = "ADD_EXERCISE_FAILURE";

export const GET_EXERCISE_SUCCESS = "GET_EXERCISE_SUCCESS";
export const GET_EXERCISE_FAILURE = "GET_EXERCISE_FAILURE";

export const UPDATE_EXERCISE_SUCCESS = "UPDATE_EXERCISE_SUCCESS";
export const UPDATE_EXERCISE_FAILURE = "UPDATE_EXERCISE_FAILURE";

export const DELETE_EXERCISE_SUCCESS = "DELETE_EXERCISE_SUCCESS";
export const DELETE_EXERCISE_FAILURE = "DELETE_EXERCISE_FAILURE";

export const GET_ONE_EXERCISE_SUCCESS = "GET_ONE_EXERCISE_SUCCESS";
export const GET_ONE_EXERCISE_FAILURE = "GET_ONE_EXERCISE_FAILURE";

export const GET_ONE_EXERCISE_SESSION_SUCCESS = "GET_ONE_EXERCISE_SESSION_SUCCESS"
export const GET_ONE_EXERCISE_SESSION_FAILURE = "GET_ONE_EXERCISE_SESSION_FAILURE"

export const GET_ONE_EXERCISE_SKILLS_SUCCESS = "GET_ONE_EXERCISE_SKILLS_SUCCESS"
export const GET_ONE_EXERCISE_SKILLS_FAILURE = "GET_ONE_EXERCISE_SKILLS_FAILURE"

// STORE Calls
export const CLEAR_CURRENT_EXERCISE_ACTION = "CLEAR_CURRENT_EXERCISE_ACTION"
export const CLEAR_EXERCISE_SESSION_ACTION = "CLEAR_EXERCISE_SESSION_ACTION"






/**
 * SEQUENCE
 */

export const CLEAR_SEQUENCE_ERROR = "CLEAR_SEQUENCE_ERROR"

// API Calls
export const GET_ALL_SEQUENCES_SUCCESS = "GET_ALL_SEQUENCES_SUCCESS";
export const GET_ALL_SEQUENCES_FAILURE = "GET_ALL_SEQUENCES_FAILURE";

export const GET_ONE_SEQUENCE_SUCCESS = "GET_ONE_SEQUENCE_SUCCESS";
export const GET_ONE_SEQUENCE_FAILURE = "GET_ONE_SEQUENCE_FAILURE";

export const ADD_SEQUENCE_SUCCESS = "ADD_SEQUENCE_SUCCESS";
export const ADD_SEQUENCE_FAILURE = "ADD_SEQUENCE_FAILURE";

export const COPY_SEQUENCE_SUCCESS = "COPY_SEQUENCE_SUCCESS";
export const COPY_SEQUENCE_FAILURE = "COPY_SEQUENCE_FAILURE";

export const UPDATE_SEQUENCE_SUCCESS = "UPDATE_SEQUENCE_SUCCESS";
export const UPDATE_SEQUENCE_FAILURE = "UPDATE_SEQUENCE_FAILURE";

export const DELETE_SEQUENCE_SUCCESS = "DELETE_SEQUENCE_SUCCESS";
export const DELETE_SEQUENCE_FAILURE = "DELETE_SEQUENCE_FAILURE";




/**
 * SKILLS
 */

export const CLEAR_SKILL_ERROR = "CLEAR_SKILL_ERROR"

// API Calls
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";
export const ADD_SKILL_FAILURE = "ADD_SKILL_FAILURE";

export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const UPDATE_SKILL_FAILURE = "UPDATE_SKILL_FAILURE";

export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_FAILURE = "DELETE_SKILL_FAILURE";

export const GET_ALL_SKILLS_SUCCESS = "GET_ALL_SKILLS_SUCCESS";
export const GET_ALL_SKILLS_FAILURE = "GET_ALL_SKILLS_FAILURE";


/**
 * USERS
 */

export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR"

// User API Actions
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const REQUEST_PASSWORD_RESET_SUCCESS = "REQUEST_PASSWORD_RESET_SUCCESS";
export const REQUEST_PASSWORD_RESET_FAILURE = "REQUEST_PASSWORD_RESET_FAILURE";

export const ACTIVATE_ACCOUNT_SUCCESS = "ACTIVATE_ACCOUNT_SUCCESS"
export const ACTIVATE_ACCOUNT_FAILURE = "ACTIVATE_ACCOUNT_FAILURE";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE"

export const GET_USER_SKILLS_SUCCESS = "GET_USER_SKILLS_SUCCESS"
export const GET_USER_SKILLS_FAILURE = "GET_USER_SKILLS_FAILURE"

export const GET_NBR_THANKS_SUCCESS = "GET_NBR_THANKS_SUCCESS"
export const GET_NBR_THANKS_FAILURE = "GET_NBR_THANKS_FAILURE"

export const SEND_THANK_SUCESS = "SEND_THANK_SUCESS"
export const SEND_THANK_FAILURE = "SEND_THANK_FAILURE"

// Message
export const CLEAR_MESSAGE_ACTION = "CLEAR_MESSAGE_ACTION";





/**
 * FEEDBACKS
 */

export const GET_ONE_FEEDBACK_SUCCESS = "GET_ONE_FEEDBACK_SUCCESS"
export const GET_ONE_FEEDBACK_FAILURE = "GET_ONE_FEEDBACK_FAILURE"

export const GET_FEEDBACKS_OF_EXERCISE_SUCCESS = "GET_FEEDBACKS_OF_EXERCISE_SUCCESS"
export const GET_FEEDBACKS_OF_EXERCISE_FAILURE = "GET_FEEDBACKS_OF_EXERCISE_FAILURE"

export const GET_ALL_WITH_STATS_SUCCESS = "GET_ALL_WITH_STATS_SUCCESS"
export const GET_ALL_WITH_STATS_FAILURE = "GET_ALL_WITH_STATS_FAILURE"

export const GET_ONE_EXERCISE_FEEDBACKS_STATS_SUCCESS = "GET_ONE_EXERCISE_FEEDBACKS_STATS_SUCCESS"
export const GET_ONE_EXERCISE_FEEDBACKS_STATS_FAILURE = "GET_ONE_EXERCISE_FEEDBACKS_STATS_FAILURE"

export const CREATE_ONE_FEEDBACK_FAILURE = "CREATE_ONE_FEEDBACK_FAILURE"

export const UPDATE_ONE_FEEDBACK_FAILURE = "UPDATE_ONE_FEEDBACK_FAILURE"

export const CLEAR_FEEDBACK_ERROR = "CLEAR_FEEDBACK_ERROR"
