#!/usr/bin/env bash
# setup-test-data.sh
#
# Creates the test data needed by the Gatling load test.
# Idempotent: safe to re-run (skips already-created accounts).
#
# What it does:
#   1. Creates 30 student accounts (student01@test.soy … student30@test.soy)
#   2. Uses the first existing session in the DB (or creates one if none exist)
#   3. Subscribes all test students to that session via SQL
#   4. Writes session/exercise IDs to load-tests/test-data.env
#
# API notes (confirmed from source):
#   POST /api/user requires: email, password, password2, firstname, lastname,
#                            locale, enabled:true
#   Activation: the 'enabled' field on the user row controls login access
#   Session subscription: INSERT INTO usersession (direct SQL — faster than API)
#
# Usage:
#   ./scripts/setup-test-data.sh [--base-url http://localhost:5001]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SOY_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

BASE_URL="${1:-}"
[[ "$BASE_URL" == --base-url ]] && { BASE_URL="$2"; shift 2; } || shift 0 2>/dev/null || true
BASE_URL="${BASE_URL:-http://localhost:5001}"

STUDENT_PASS="SoYTest2024!"
N_STUDENTS=30
TEST_DATA_FILE="$SOY_DIR/load-tests/test-data.env"
DB_CONTAINER="soy_postgres"
DB_USER="plagedba"
DB_NAME="plagedb"

ok()   { echo "  ✓ $*"; }
skip() { echo "  – $* (skipped)"; }
err()  { echo "  ✗ $*" >&2; }

psql_exec() { docker exec "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -t -c "$1" 2>/dev/null; }

# ── Wait for gateway ──────────────────────────────────────
echo "Waiting for gateway at $BASE_URL..."
for i in $(seq 1 30); do
  if curl -s --max-time 3 "$BASE_URL/api/auth/verify" -o /dev/null; then
    echo "Gateway is up."; break
  fi
  echo "  Attempt $i/30 – retrying in 3s..."; sleep 3
  [[ $i -eq 30 ]] && { err "Gateway did not respond"; exit 1; }
done

# ── Create 30 student accounts ────────────────────────────
echo ""
echo "Creating $N_STUDENTS student accounts..."
CREATED=0; SKIPPED=0
for i in $(seq -w 1 $N_STUDENTS); do
  EMAIL="student${i}@test.soy"
  RESP=$(curl -s --max-time 5 -X POST "$BASE_URL/api/user" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$EMAIL\",\"password\":\"$STUDENT_PASS\",\"password2\":\"$STUDENT_PASS\",\"firstname\":\"Student\",\"lastname\":\"$i\",\"locale\":\"en\",\"enabled\":true}" 2>/dev/null || true)
  if echo "$RESP" | grep -q user_id; then CREATED=$((CREATED+1))
  else SKIPPED=$((SKIPPED+1)); fi
done
ok "Students: $CREATED created, $SKIPPED already exist"

# ── Pick the session to use ───────────────────────────────
# Use the first session in the DB. The 'session' table has ps_id + name.
SESSION_ID=$(psql_exec "SELECT ps_id FROM session ORDER BY ps_id LIMIT 1;" | tr -d ' \n' || echo "")
if [[ -z "$SESSION_ID" ]]; then
  skip "No sessions found in DB — create one manually via the instructor UI"
  SESSION_ID=1
else
  ok "Using session ps_id=$SESSION_ID"
fi

# ── Subscribe all test students to the session ────────────
echo ""
echo "Subscribing all test students to session $SESSION_ID..."
SUB_COUNT=$(psql_exec "
  INSERT INTO usersession (user_id, ps_id)
  SELECT u.user_id, $SESSION_ID FROM soyuser u
  WHERE u.email LIKE '%@test.soy' AND u.role_id = 3
  ON CONFLICT DO NOTHING;
  SELECT count(*) FROM usersession us
  JOIN soyuser u ON us.user_id = u.user_id
  WHERE u.email LIKE '%@test.soy' AND us.ps_id = $SESSION_ID;
" | grep -E "^[[:space:]]*[0-9]" | tr -d ' ' || echo "?")
ok "Students subscribed to session $SESSION_ID: $SUB_COUNT"

# ── Pick an exercise ──────────────────────────────────────
EXERCISE_ID=$(psql_exec "SELECT ex_id FROM exercise WHERE state = 'Available' ORDER BY ex_id LIMIT 1;" | tr -d ' \n' || echo "1")
EXERCISE_ID="${EXERCISE_ID:-1}"
ok "Using exercise ex_id=$EXERCISE_ID"

# ── Ensure accounts are enabled ──────────────────────────
# (The 'enabled' field controls login access, not 'activated')
ENABLED=$(psql_exec "UPDATE soyuser SET enabled=true WHERE email LIKE '%@test.soy'; SELECT count(*) FROM soyuser WHERE email LIKE '%@test.soy' AND enabled=true;" | grep -E "^[[:space:]]*[0-9]" | tr -d ' ' || echo "?")
ok "Enabled accounts: $ENABLED"

# ── Write test-data.env ───────────────────────────────────
cat > "$TEST_DATA_FILE" <<EOF
# Auto-generated by scripts/setup-test-data.sh – $(date)
SESSION_ID=$SESSION_ID
EXERCISE_ID=$EXERCISE_ID
BASE_URL=$BASE_URL
EOF
ok "Written to $TEST_DATA_FILE"

echo ""
echo "✓  Test data setup complete."
echo "   Session  : $SESSION_ID"
echo "   Exercise : $EXERCISE_ID"
echo "   Students : student01@test.soy … student${N_STUDENTS}@test.soy  / $STUDENT_PASS"
echo ""
echo "   Next: ./scripts/run-load-test.sh --variant 1 --pattern http"
